#!/bin/bash

dir="$(dirname "$0")"

source $dir/functions/third-party/google-chrome
source $dir/functions/third-party/rvm
source $dir/functions/third-party/spotify
source $dir/functions/third-party/sublime-text-3

# Install Third-Party Applications
function thirdparty {
    eval `resize`
    THIRDPARTY=$(whiptail \
        --notags \
        --title "Third-Party Installation" \
        --menu "\nWhat third-party software would you like to install?" \
        --ok-button "Install" \
        --cancel-button "Go Back" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        'google-chrome'     'Google Chrome' \
        'rvm'               'Ruby Version Manager (RVM)' \
        'spotify'           'Spotify' \
        'sublime-text-3'      'Sublime Text 3' \
        3>&1 1>&2 2>&3)
     
    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        $THIRDPARTY
    else
        main
    fi
}